"""empty message

Revision ID: 8a00343ccd88
Revises: 9c59c278859e
Create Date: 2025-03-17 09:45:54.161411

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a00343ccd88'
down_revision = '9c59c278859e'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='文件名'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='地址'),
    sa.Column('size', sa.Integer(), nullable=True, comment='大小(MB)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件表'
    )
    op.create_table('job',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('job_name', sa.String(length=32), nullable=True, comment='任务名称'),
    sa.Column('parent_job_id', sa.String(length=32), nullable=True, comment='父任务号'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.Column('comment', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('creat_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务表'
    )
    op.create_table('job_result',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('job_id', sa.Integer(), nullable=True, comment='任务Id'),
    sa.Column('file_id', sa.Integer(), nullable=True, comment='文件Id'),
    sa.Column('result_key', sa.String(length=64), nullable=True, comment='关键字'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务结果表'
    )
    op.create_table('sample',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('species', sa.String(length=64), nullable=True, comment='物种'),
    sa.Column('sample_id', sa.String(length=64), nullable=True, comment='样本名'),
    sa.Column('project_id', sa.String(length=64), nullable=True, comment='项目名'),
    sa.Column('tissue', sa.String(length=64), nullable=True, comment='组织、器官'),
    sa.Column('cell_count', sa.Integer(), nullable=True, comment='细胞数'),
    sa.Column('project_title', sa.String(length=255), nullable=True, comment='项目标题'),
    sa.Column('project_summary', sa.String(length=1024), nullable=True, comment='项目总结'),
    sa.Column('platform', sa.String(length=64), nullable=True, comment='测序平台'),
    sa.Column('ext', sa.String(length=1024), nullable=True, comment='扩展字段'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='样本表'
    )
    op.drop_index('idx_status_nickname', table_name='sys_user')
    op.drop_index('ix_sys_user_username', table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index('ix_gen_field_db_field_id', table_name='gen_field')
    op.drop_index('ix_gen_field_db_table_id', table_name='gen_field')
    op.drop_table('gen_field')
    op.drop_index('idx_parent_id', table_name='sys_menu')
    op.drop_table('sys_menu')
    op.drop_table('db_index')
    op.drop_table('sys_dict_data')
    op.drop_table('db_connection')
    op.drop_table('member')
    op.drop_table('sys_user_role')
    op.drop_index('ix_db_database_connection_id', table_name='db_database')
    op.drop_table('db_database')
    op.drop_table('sys_role')
    op.drop_table('sys_role_menu')
    op.drop_table('read_new_word')
    op.drop_index('ix_db_field_table_id', table_name='db_field')
    op.drop_table('db_field')
    op.drop_index('ix_gen_table_database_id', table_name='gen_table')
    op.drop_index('ix_gen_table_db_table_id', table_name='gen_table')
    op.drop_table('gen_table')
    op.drop_table('java_project_structure')
    op.drop_index('dict_type', table_name='sys_dict_type')
    op.drop_table('sys_dict_type')
    op.drop_index('ix_db_table_database_id', table_name='db_table')
    op.drop_table('db_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_table',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('database_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='数据库id'),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False, comment='表名称'),
    sa.Column('comment', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='表结构信息',
    mysql_comment='表结构信息',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_db_table_database_id', 'db_table', ['database_id'], unique=False)
    op.create_table('sys_dict_type',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True, comment='字典名称'),
    sa.Column('type', mysql.VARCHAR(length=64), nullable=True, comment='字典类型'),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='状态(1正常 0停用)'),
    sa.Column('comment', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典类型表',
    mysql_comment='字典类型表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('dict_type', 'sys_dict_type', ['type'], unique=True)
    op.create_table('java_project_structure',
    sa.Column('id', mysql.BIGINT(display_width=11), autoincrement=True, nullable=False),
    sa.Column('path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_file', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('parent_id', mysql.BIGINT(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('gen_table',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('database_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='数据库ID'),
    sa.Column('db_table_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='数据库表ID'),
    sa.Column('table_name', mysql.VARCHAR(length=64), nullable=True, comment='表名'),
    sa.Column('sub_table_name', mysql.VARCHAR(length=64), nullable=True, comment='关联子表的表名'),
    sa.Column('sub_table_fk_name', mysql.VARCHAR(length=64), nullable=True, comment='子表关联的外键名'),
    sa.Column('class_name', mysql.VARCHAR(length=64), nullable=True, comment='实体类名称'),
    sa.Column('backend', mysql.VARCHAR(length=16), nullable=True, comment='后端语言'),
    sa.Column('tpl_category', mysql.VARCHAR(length=64), nullable=True, comment='使用的模板（crud单表操作 tree树表操作）'),
    sa.Column('tpl_web_type', mysql.VARCHAR(length=32), nullable=True, comment='前端模板类型'),
    sa.Column('tpl_backend_type', mysql.VARCHAR(length=32), nullable=True, comment='后端模板类型'),
    sa.Column('package_name', mysql.VARCHAR(length=128), nullable=True, comment='生成包路径'),
    sa.Column('module_name', mysql.VARCHAR(length=32), nullable=True, comment='生成模块名'),
    sa.Column('business_name', mysql.VARCHAR(length=32), nullable=True, comment='生成业务名'),
    sa.Column('function_name', mysql.VARCHAR(length=32), nullable=True, comment='生成功能名'),
    sa.Column('function_author', mysql.VARCHAR(length=32), nullable=True, comment='生成功能作者'),
    sa.Column('gen_type', mysql.VARCHAR(length=1), nullable=True, comment='生成代码方式（0zip压缩包 1自定义路径）'),
    sa.Column('gen_path', mysql.VARCHAR(length=255), nullable=True, comment='生成路径（不填默认项目路径）'),
    sa.Column('options', mysql.VARCHAR(length=255), nullable=True, comment='其它生成选项'),
    sa.Column('comment', mysql.VARCHAR(length=64), nullable=True, comment='表描述'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='代码生成业务表',
    mysql_comment='代码生成业务表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_gen_table_db_table_id', 'gen_table', ['db_table_id'], unique=False)
    op.create_index('ix_gen_table_database_id', 'gen_table', ['database_id'], unique=False)
    op.create_table('db_field',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('table_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='表id'),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False, comment='字段名称'),
    sa.Column('type', mysql.VARCHAR(length=32), nullable=False, comment='字段类型'),
    sa.Column('length', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='总长度'),
    sa.Column('scale', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='小数长度'),
    sa.Column('default', mysql.VARCHAR(length=64), nullable=True, comment='默认值'),
    sa.Column('comment', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.Column('nullable', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='允许为空(0否,1是)'),
    sa.Column('primary_key', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='主键(0否,1是)'),
    sa.Column('autoincrement', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='自增(0否,1是)'),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='字段信息表',
    mysql_comment='字段信息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_db_field_table_id', 'db_field', ['table_id'], unique=False)
    op.create_table('read_new_word',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('word', mysql.VARCHAR(length=32), nullable=True, comment='单词'),
    sa.Column('translation', mysql.VARCHAR(length=32), nullable=True, comment='翻译'),
    sa.Column('next_review_date', mysql.DATETIME(), nullable=True, comment='复习时间'),
    sa.Column('tenant', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='租户ID'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_role_menu',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='自增编号'),
    sa.Column('role_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='角色ID'),
    sa.Column('menu_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='菜单ID'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色和菜单关联表',
    mysql_comment='角色和菜单关联表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_role',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='角色ID'),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False, comment='角色名称'),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=False, comment='角色权限字符串'),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='显示顺序'),
    sa.Column('data_scope', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）'),
    sa.Column('data_scope_dept_ids', mysql.VARCHAR(length=500), nullable=True, comment='数据范围(指定部门数组)'),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='角色状态（0正常 1停用）'),
    sa.Column('comment', mysql.VARCHAR(length=500), nullable=True, comment='备注'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色信息表',
    mysql_comment='角色信息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('db_database',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('connection_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='数据库连接id'),
    sa.Column('database_name', mysql.VARCHAR(length=64), nullable=False, comment='数据库名称'),
    sa.Column('owner', mysql.VARCHAR(length=64), nullable=True, comment='拥有者'),
    sa.Column('template', mysql.VARCHAR(length=64), nullable=True, comment='使用模板'),
    sa.Column('encoding', mysql.VARCHAR(length=32), nullable=True, comment='字符编码'),
    sa.Column('collation_order', mysql.VARCHAR(length=32), nullable=True, comment='排序规则'),
    sa.Column('character_classification', mysql.VARCHAR(length=32), nullable=True, comment='字符分类'),
    sa.Column('tablespace', mysql.VARCHAR(length=64), nullable=True, comment='表空间名称'),
    sa.Column('connection_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='连接限制'),
    sa.Column('allow_connection', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否允许连接'),
    sa.Column('is_template', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否为模板数据库'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据库信息表',
    mysql_comment='数据库信息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_db_database_connection_id', 'db_database', ['connection_id'], unique=False)
    op.create_table('sys_user_role',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='自增编号'),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('role_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='角色ID'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户和角色关联表',
    mysql_comment='用户和角色关联表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('member',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='名称'),
    sa.Column('nation', mysql.VARCHAR(length=255), nullable=True, comment='国家'),
    sa.Column('gender', mysql.CHAR(length=1), nullable=True, comment='性别'),
    sa.Column('birthday', mysql.DATETIME(), nullable=True, comment='生日'),
    sa.Column('hobby', mysql.VARCHAR(length=255), nullable=True, comment='爱好'),
    sa.Column('parent_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='父Id'),
    sa.PrimaryKeyConstraint('id'),
    comment='会员管理',
    mysql_comment='会员管理',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('db_connection',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('connection_name', mysql.VARCHAR(length=32), nullable=False, comment='连接名称'),
    sa.Column('database_type', mysql.VARCHAR(length=16), nullable=False, comment='数据库类型'),
    sa.Column('connection_database', mysql.VARCHAR(length=64), nullable=True, comment='连接数据库名称'),
    sa.Column('host', mysql.VARCHAR(length=16), nullable=True, comment='主机'),
    sa.Column('port', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='端口号'),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=True, comment='用户名'),
    sa.Column('password', mysql.VARCHAR(length=64), nullable=True, comment='密码'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='连接信息表',
    mysql_comment='连接信息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_dict_data',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='字典排序'),
    sa.Column('label', mysql.VARCHAR(length=64), nullable=True, comment='字典标签'),
    sa.Column('value', mysql.VARCHAR(length=64), nullable=True, comment='字典键值'),
    sa.Column('type', mysql.VARCHAR(length=64), nullable=True, comment='字典类型'),
    sa.Column('echo_style', mysql.VARCHAR(length=64), nullable=True, comment='回显样式'),
    sa.Column('ext_class', mysql.VARCHAR(length=64), nullable=True, comment='扩展样式'),
    sa.Column('is_default', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='是否默认(1是 0否)'),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='状态(1正常 0停用)'),
    sa.Column('comment', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典数据表',
    mysql_comment='字典数据表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('db_index',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('table_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='表id'),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False, comment='索引名称'),
    sa.Column('field', mysql.VARCHAR(length=64), nullable=False, comment='索引字段'),
    sa.Column('type', mysql.VARCHAR(length=16), nullable=False, comment='索引类型'),
    sa.Column('remark', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='索引信息表',
    mysql_comment='索引信息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_menu',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False, comment='名称'),
    sa.Column('icon', mysql.VARCHAR(length=100), nullable=True, comment='图标'),
    sa.Column('permission', mysql.VARCHAR(length=100), nullable=True, comment='权限标识'),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('path', mysql.VARCHAR(length=200), nullable=True, comment='路由地址'),
    sa.Column('component', mysql.VARCHAR(length=255), nullable=True, comment='组件路径'),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='类型（1目录 2菜单 3按钮）'),
    sa.Column('cacheable', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='是否缓存（1缓存 0不缓存）'),
    sa.Column('visible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='是否显示（1显示 0隐藏）'),
    sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='父ID'),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='状态（1正常 0停用）'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('comment', mysql.VARCHAR(length=500), nullable=True, comment='备注信息'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统菜单表',
    mysql_comment='系统菜单表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('idx_parent_id', 'sys_menu', ['parent_id'], unique=False)
    op.create_table('gen_field',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('db_table_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='数据库表ID'),
    sa.Column('db_field_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='数据库字段ID'),
    sa.Column('field_name', mysql.VARCHAR(length=64), nullable=True, comment='字段名称'),
    sa.Column('field_type', mysql.VARCHAR(length=64), nullable=True, comment='字段类型'),
    sa.Column('sql_model_type', mysql.VARCHAR(length=64), nullable=True, comment='模型类型'),
    sa.Column('length', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='字段长度'),
    sa.Column('scale', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='分数位'),
    sa.Column('js_type', mysql.VARCHAR(length=64), nullable=True, comment='JS类型'),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('default', mysql.VARCHAR(length=64), nullable=True, comment='默认值'),
    sa.Column('primary_key', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='是否主键(0否,1是)'),
    sa.Column('nullable', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='允许为空(0否,1是)'),
    sa.Column('creatable', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='创建字段(0否,1是)'),
    sa.Column('queryable', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='查询字段(0否,1是)'),
    sa.Column('pageable', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='列表字段(0否,1是)'),
    sa.Column('detailable', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='详情字段(0否,1是)'),
    sa.Column('modifiable', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='修改字段(0否,1是)'),
    sa.Column('batch_modifiable', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='批量修改(0否,1是)'),
    sa.Column('query_type', mysql.VARCHAR(length=64), nullable=True, comment='查询方式（等于、不等于、大于、小于、范围）'),
    sa.Column('html_type', mysql.VARCHAR(length=64), nullable=True, comment='显示类型(文本框、文本域、下拉框、复选框、单选框、日期控件)'),
    sa.Column('dict_type', mysql.VARCHAR(length=64), nullable=True, comment='字典类型'),
    sa.Column('comment', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='代码生成字段表',
    mysql_comment='代码生成字段表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_gen_field_db_table_id', 'gen_field', ['db_table_id'], unique=False)
    op.create_index('ix_gen_field_db_field_id', 'gen_field', ['db_field_id'], unique=False)
    op.create_table('sys_user',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('username', mysql.VARCHAR(length=32), nullable=False, comment='用户名'),
    sa.Column('password', mysql.VARCHAR(length=63), nullable=False, comment='密码'),
    sa.Column('nickname', mysql.VARCHAR(length=32), nullable=False, comment='昵称'),
    sa.Column('avatar_url', mysql.VARCHAR(length=63), nullable=True, comment='头像地址'),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='状态(0:停用,1:待审核,2:正常,3:已注销)'),
    sa.Column('remark', mysql.VARCHAR(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户信息表',
    mysql_comment='用户信息表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sys_user_username', 'sys_user', ['username'], unique=True)
    op.create_index('idx_status_nickname', 'sys_user', ['status', 'nickname'], unique=False)
    op.drop_table('sample')
    op.drop_table('job_result')
    op.drop_table('job')
    op.drop_table('file')
    # ### end Alembic commands ###
