"""empty message

Revision ID: 46f1f38e0db1
Revises: 
Create Date: 2025-06-27 11:22:05.879746

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '46f1f38e0db1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='文件名'),
    sa.Column('path', sa.String(length=255), nullable=True, comment='地址'),
    sa.Column('size', sa.Integer(), nullable=True, comment='大小(MB)'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件表'
    )
    op.create_table('job',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('job_name', sa.String(length=32), nullable=True, comment='任务名称'),
    sa.Column('parent_job_id', sa.String(length=32), nullable=True, comment='父任务号'),
    sa.Column('status', sa.Integer(), nullable=True, comment='状态'),
    sa.Column('comment', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('creat_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务表'
    )
    op.create_table('job_result',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('job_id', sa.Integer(), nullable=True, comment='任务Id'),
    sa.Column('file_id', sa.Integer(), nullable=True, comment='文件Id'),
    sa.Column('result_key', sa.String(length=64), nullable=True, comment='关键字'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务结果表'
    )
    op.create_table('sample',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('species', sa.String(length=64), nullable=True, comment='物种'),
    sa.Column('sample_id', sa.String(length=64), nullable=True, comment='样本名'),
    sa.Column('project_id', sa.String(length=64), nullable=True, comment='项目名'),
    sa.Column('tissue', sa.String(length=64), nullable=True, comment='组织、器官'),
    sa.Column('cell_count', sa.Integer(), nullable=True, comment='细胞数'),
    sa.Column('project_title', sa.String(length=255), nullable=True, comment='项目标题'),
    sa.Column('project_summary', sa.String(length=1024), nullable=True, comment='项目总结'),
    sa.Column('platform', sa.String(length=64), nullable=True, comment='测序平台'),
    sa.Column('ext', sa.String(length=1024), nullable=True, comment='扩展字段'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='样本表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    op.drop_table('job_result')
    op.drop_table('job')
    op.drop_table('file')
    # ### end Alembic commands ###
