"""empty message

Revision ID: 89581cb48fc7
Revises: 46f1f38e0db1
Create Date: 2025-06-27 15:15:59.592195

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
import pgvector


# revision identifiers, used by Alembic.
revision = '89581cb48fc7'
down_revision = '46f1f38e0db1'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('barcode', sa.String(length=255), nullable=True, comment='细胞标识'),
    sa.Column('sample_id', sa.String(length=255), nullable=True, comment='样本ID'),
    sa.Column('assay', sa.String(length=255), nullable=True, comment='测序平台'),
    sa.Column('organism', sa.String(length=255), nullable=True, comment='物种'),
    sa.Column('development_stage', sa.String(length=255), nullable=True, comment='发育阶段'),
    sa.Column('tissue', sa.String(length=255), nullable=True, comment='组织类型'),
    sa.Column('disease', sa.String(length=255), nullable=True, comment='疾病状态'),
    sa.Column('sex', sa.String(length=50), nullable=True, comment='性别'),
    sa.Column('cell_type', sa.String(length=255), nullable=True, comment='细胞类型'),
    sa.Column('cell_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True, comment='细胞向量'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='元数据表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    # ### end Alembic commands ###
